name: Lint

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Linting
      uses: j2kun/chktex-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
